use aoc_2024::*;

fn main() {
    let input = r#"....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
"#;

    // dbg!(atoi_radix10::parse::<u32>(b"123"));

    let input = include_str!("../../inputs/day06.txt");

    let part1 = day06::part2(input);
    dbg!(part1);
}
