pub mod day01_fast;
pub mod day02_fast;
pub mod day03_fast;
pub mod day06_fast;
pub mod day07_fast;
pub mod day08_fast;
pub mod day09_fast;
pub mod day10_fast;
// pub mod day11_fast;
pub mod day13_fast;
